version: '3'

networks:
  app-network:
    driver: bridge

services:
  db:
    image: postgres
    restart: always
    volumes: 
      - ./data/db:/var/lib/postgresql/data
    networks:
      - app-network
    environment:
      - POSTGRES_DB=testDB
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    networks:
      - app-network

  nest:
    build: ./PoC-backend
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - DATABASE_URL=postgresql://user:postgres@db:5432/testDB?schema=public
    command: ["/wait-for-it.sh", "db:5432", "--", "npm", "run", "start"]

  frontend:
    build: ./PoC-frontend
    ports:
      - 4200:4200
    depends_on:
      - nest
    networks:
      - app-network
    command: ng serve --host 0.0.0.0 --port 4200
