version: '3'

networks:
  database:
    driver: bridge

services:
  db:
    image: postgres
    restart: always
    volumes: 
      - ./data/db:/var/lib/postgresql/data
    networks:
      - database
    environment:
      - POSTGRES_DB=testDB
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    networks:
      - database

  nest:
    build: ./
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - database
    environment:
      - DATABASE_URL=postgresql://user:postgres@db:5432/testDB?schema=public
